const infor_project = [
    {
        flagNumber: 2,
        linkView: "https://nino.is-a.dev/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(1).jpg",
        dateDev: "2023-11-02", 
        source: "",
        name: "My Card Information",
        description: "Hihi", 
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 3,
        linkView: "https://nino.is-a.dev/MyOfficialWebsite/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(2).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "My official website",
        description: "Quite a bit of information about me.",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 2,
        linkView: "https://nino.is-a.dev/MyGameServiceWebsite/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(3).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "My Game Service Website",
        description: "!!",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 3,
        linkView: "https://nino.is-a.dev/CharacterChampionsLeague/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(4).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "Character Champions League",
        description: "!!",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 2,
        linkView: "https://nino.is-a.dev/HonkaiStarRailLoadingHTML-CSS/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(5).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "Honkai Star Rail Loading HTML-CSS",
        description: "!!",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 3,
        linkView: "https://nino.is-a.dev/FreeStickersHoyolab/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(6).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "Free sticker Hoyolab to use Discord",
        description: "!!",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },
    {
        flagNumber: 2,
        linkView: "https://nino.is-a.dev/Valentine_UwU/",
        img: "./assets/images/HoshinoAi/horizontal/HoshinoAi(7).jpg",
        dateDev: "2023-11-24",
        source: "#",
        name: "Valentine 2024 | Nino & Yu",
        description: "!!",
        language: "HTML, CSS, JS",
        collection: Math.floor(Math.random() * 20),
    },



    // {
    //     flagNumber: ,
    //     linkView: "",
    //     img: "./assets/image/HoshinoAi/horizontal/HoshinoAi(5).jpg",
    //     dateDev: "2023-11-24",
    //     source: "#",
    //     name: "",
    //     description: "!!",
    //     language: "HTML, CSS, JS",
    //     collection: Math.floor(Math.random() * 20),
    // },
]

export { infor_project };